# Generated by Django 4.1.6 on 2023-03-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='recomendation',
            field=models.FloatField(default=0),
        ),
    ]
